### ISSUE TITLE
Escape `\`  in attribute values to make valid JSON

### ISSUE THREAD

**Issue by slafayIGN** [rok4/core-cpp#10]
Backslashes `\` should be escaped when present among the attribute values here : 

https://github.com/rok4/core-cpp/blob/226deb19f6a1fbdc74b6a1de6d23fa0c5dea96b1/include/rok4/utils/Attribute.h#L143-L145

Otherwise, the `metadata.json` is invalid and client apps cannot read it.

Example of invalid JSON : https://vt-gpf-beta.ign.fr/tms/1.0.0/tuiles_urba/metadata.json

**Comment by lowzonenose** [comment]
Une solution simple pour doubler les **backslash** (en évitant de traiter les **backslash** déjà doublés)
![image](https://github.com/rok4/core-cpp/assets/10401006/25812d51-c1d1-4326-be0c-978fd66cb76c)
