### ISSUE TITLE
Gérer le multi cluster S3

### ISSUE THREAD

**Issue by Dolite** [rok4/core-cpp#11]
Afin qu'un serveur ROK4 puisse manipuler des pyramides réparties dans plusieurs clusters S3, il faut implémenter l'évolution déjà mise en place en python au niveau de l'annuaire de stockage.

Comme pour la partie python, la syntaxe est la suivante :

- les variables d'environnement `ROK4_S3_KEY`, `ROK4_S3_SECRETKEY` et `ROK4_S3_URL` sont considérées comme des listes (potentiellement à un seul élément, comme avant). Exemple avec deux clusters :
```
ROK4_S3_KEY=KEY1,KEY2
ROK4_S3_SECRETKEY=SKEY1,SKEY2
ROK4_S3_URL=https://s3.storage.fr:1234,https://s4.storage.fr
```
- le nom du bucket dans le chemin du descripteur de pyramide (précisé dans le descripteur de couche) peut être de la forme <nom du bucket>@<host du cluster> : sans la partie host, on considèrera qu'on travaille avec le cluster par défaut, le premier décrit. Exemple : `bucket1@s4.storage.fr` : si le host précisé ne correspond à aucun cluster renseigné en variable d'environnement, il faut raler. `bucket_toto` et `bucket_toto@s3.storage.fr:1234` sont équivalent avec l'exemple précédant.

**Comment by lowzonenose** [comment]
Un lien possible vers cette évolution : https://github.com/rok4/core-perl/pull/2 avec **Region S3**
